### ISSUE TITLE
Unnecessary parentheses

### ISSUE THREAD

**Issue by axion014** [stackgl/glsl-min-stream#5]
Repost from TimvanScherpenzeel/glsl-minifier#2.

**Comment by axion014** [comment]
@stackgl sorry for mentioning the entire team, have anyone got into this? do I have to write the fix myself? it's been long since first post.
Those grouping operators is making the minified file bigger than original.

**Comment by dhritzkiv** [comment]
Hi @axion014. The original maintainers have likely moved on to new projects and won’t be able to contribute fixes.

If you see a clear fix to your issue, please feel free to submit a pull request, and I will review it.
